### ISSUE TITLE
Some systems failed to build for Quicklisp dist

### ISSUE THREAD

**Issue by quicklisp** [guicho271828/trivialib.bdd#2]
Building with SBCL 2.1.10 / ASDF 3.3.5 for quicklisp dist creation.

Trying to build commit id b4fe30d3b6e366d1bdce74093e849bbe1e4f4f14

*trivialib.bdd.test* fails to build because of a failure in  _trivialib.bdd_.

*trivialib.bdd* fails to build with the following error:

```
; caught WARNING:
;   * is not permitted as an argument to the FUNCTION type specifier
; 
; caught WARNING:
;   * is not permitted as an argument to the FUNCTION type specifier
...
Unhandled UIOP/LISP-BUILD:COMPILE-FILE-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING {1001C08103}>: COMPILE-FILE-ERROR while compiling #<CL-SOURCE-FILE "trivialib.bdd" "2.odd">

```

[Full log here](http://report.quicklisp.org/2021-11-02/failure-report/trivialib.bdd.html)

**Comment by guicho271828** [comment]
this is fixed
